export function generateManifest(siteName = 'My Site', themeColor = '#a3e635') {
  const manifest = {
    name: siteName,
    short_name: siteName,
    icons: [
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
      },
    ],
    theme_color: themeColor,
    background_color: '#ffffff',
    display: 'standalone',
  }

  return JSON.stringify(manifest, null, 2)
}

export function generateHtmlSnippet(options = {}) {
  const { includeSVG = false, themeColor = '#a3e635' } = options

  return `<!-- Favicon Package Generated by FAVGEN -->
<!-- Place these files in your site root -->

<!-- Standard favicon -->
<link rel="icon" type="image/x-icon" href="/favicon.ico">

<!-- PNG fallbacks -->
<link rel="icon" type="image/png" sizes="16x16" href="/16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/32.png">
<link rel="icon" type="image/png" sizes="48x48" href="/48.png">

<!-- Apple Touch Icon -->
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

<!-- Android Chrome -->
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png">

${includeSVG ? '<!-- SVG for modern browsers -->\n<link rel="icon" type="image/svg+xml" href="/favicon.svg">\n' : ''}
<!-- Web App Manifest -->
<link rel="manifest" href="/manifest.json">

<!-- Theme color for mobile browsers -->
<meta name="theme-color" content="${themeColor}">

<!-- Microsoft Tiles -->
<meta name="msapplication-TileColor" content="${themeColor}">
<meta name="msapplication-TileImage" content="/android-chrome-512x512.png">`
}

export function generateSVG(canvas) {
  const dataUrl = canvas.toDataURL('image/png')

  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64">
  <image href="${dataUrl}" width="64" height="64"/>
</svg>`
}
